spring:
  application:
    name: RestApiHttpMethods

  datasource:
    url: jdbc:sqlserver://TNS-IT-DESKTOP;instanceName=SQLEXPRESS;databaseName=RestApiHttpMethodsDB;integratedSecurity=true;encrypt=false;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080